"""
Django settings for isamauto project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import pymysql
pymysql.install_as_MySQLdb()

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-e^*&4@yz&rl99olv7pm$pt*it%9u2%9sca9v*_7ozy@8=n0m#+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['admin.isamauto.ca']
CSRF_TRUSTED_ORIGINS = [
    'https://admin.isamauto.ca/',
    'http://admin.isamauto.ca',   # optional
]

CORS_ALLOW_CREDENTIALS = True



X_FRAME_OPTIONS = 'SAMEORIGIN'
# Application definition

INSTALLED_APPS = [
    "jazzmin", 
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'site_setting',
    'car_listing',
    'page_content',
    'loan_application',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'isamauto.urls'
WSGI_APPLICATION = 'isamauto.wsgi.application'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
}


CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOW_HEADERS = [
    "Origin",
    "X-Requested-With",
    "Content-Type",
    "Accept",
    "Authorization",
]

WSGI_APPLICATION = 'isamauto.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE':   'django.db.backends.mysql',
        'NAME':     'travell2_isamauto',      # your database name
        'USER':     'travell2_isamauto',      # your MySQL user
        'PASSWORD': 'sYNraUzY;etH',           # your MySQL password
        'HOST':     'localhost',              # or your DB host/IP
        'PORT':     '3306',                   # default MySQL port
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'charset': 'utf8mb4',
        },
    }
}

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'isamauto.ca'
EMAIL_PORT = 465
EMAIL_USE_TLS = False 
EMAIL_USE_SSL = True
EMAIL_HOST_USER = 'noreply@isamauto.ca' 
EMAIL_HOST_PASSWORD = 'IdpcKQFZZ0.%'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/uploads/'
MEDIA_ROOT = BASE_DIR / 'uploads'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


JAZZMIN_SETTINGS = {
    "site_title":    "Isam Auto Admin",
    "site_header":   "Isam Auto Backend",
    "site_brand":    "Isam Auto",

    "hide_apps": ["auth"],

    "site_logo":       "admin_design/logos/logo.png",       
    "site_logo_dark":  "admin_design/logos/logo.png",   

    "site_icon":       "admin_design/logos/logo.png",

    "login_logo":      "admin_design/logos/logo.png",
    
    "welcome_sign":  "Welcome to Isam Auto Dashboard",
    
    "topmenu_links": [
        {"name": "Home",    "url": "/",           "icon": "fa fa-home"},
    ],

    "icons": {
        "site_setting.Settings": "fas fa-cog",
        "car_listing.CarListing":     "fas fa-car-side",
        "car_listing.CarType":        "fas fa-car",
        "car_listing.CarBrand":       "fas fa-tag",
        "car_listing.CarBodyType":    "fas fa-car-crash",
        "car_listing.CarModel":       "fas fa-cogs",
        "car_listing.CarDealer":      "fas fa-store",
        "car_listing.FuelType":       "fas fa-gas-pump",
        "car_listing.DriveType":      "fas fa-road",
        "car_listing.GearType":       "fas fa-cog",
        "car_listing.Feature":        "fas fa-star",
        "car_listing.OwnerType":      "fas fa-user-tie",
        "car_listing.ModelYear":      "fas fa-calendar-alt",
        "car_listing.CarImage":       "fas fa-images",
    },
    
    "show_ui_builder": False,
    "ismobile":         False,
    
    "custom_css":      "admin_design/css/jazzmin-custom.css",
    "custom_js":       "admin_design/js/jazzmin-custom.js",

    "related_modal_active": True,

        "order_with_respect_to": [
        "car_listing.CarListing",
        "car_listing.CarImage",
        "car_listing.CarDealer",
        "car_listing.CarBrand",
        "car_listing.CarBodyType",
        "car_listing.CarType",
        "car_listing.CarModel",
        "car_listing.Feature",
        "car_listing.FuelType",
        "car_listing.DriveType",
        "car_listing.GearType",
        "car_listing.OwnerType",
        "car_listing.ModelYear",
    ],
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": True,
    "brand_small_text": False,
    "brand_colour": "navbar-danger",
    "accent": "accent-navy",
    "navbar": "navbar-danger navbar-dark",
    "no_navbar_border": True,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-light-danger",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": True,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "cerulean",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    },
    "actions_sticky_top": True
}