# Generated by Django 5.2 on 2025-05-05 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarBodyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='car_body/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='car_brands/logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarDealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='car_dealers/images/')),
                ('location', models.TextField(help_text='Google Maps embed code')),
                ('contact_number', models.CharField(max_length=20, unique=True)),
                ('whatsapp_link', models.URLField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car_listings/images/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DriveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GearType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OwnerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('video_url', models.URLField(blank=True, max_length=255, null=True)),
                ('carfax', models.FileField(blank=True, null=True, upload_to='car_listings/carfax/')),
                ('mileage', models.PositiveIntegerField()),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthly_installment_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('installment_month', models.PositiveIntegerField(blank=True, null=True)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('cylinders', models.PositiveIntegerField()),
                ('stock_number', models.CharField(max_length=100, unique=True)),
                ('vin_number', models.CharField(max_length=100, unique=True)),
                ('engine_size', models.CharField(max_length=50)),
                ('doors', models.PositiveIntegerField()),
                ('colors', models.CharField(max_length=100)),
                ('seats', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('On Sale', 'On Sale'), ('Featured', 'Featured'), ('Sold Car', 'Sold Car')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_listing.carbodytype')),
                ('car_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_listing.carbrand')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_listing.cardealer')),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_for', to='car_listing.carimage')),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_listing.carmodel')),
                ('car_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_listing.cartype')),
                ('drive_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_listing.drivetype')),
                ('features', models.ManyToManyField(blank=True, to='car_listing.feature')),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_listing.fueltype')),
                ('gear_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_listing.geartype')),
                ('model_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_listing.modelyear')),
                ('owner_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_listing.ownertype')),
            ],
        ),
        migrations.AddField(
            model_name='carimage',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='car_listing.carlisting'),
        ),
    ]
