# Generated by Django 5.2 on 2025-05-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_listing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carlisting',
            name='featured_image',
        ),
        migrations.AddField(
            model_name='carimage',
            name='is_featured',
            field=models.BooleanField(default=False, help_text="Tick to make this the listing's featured image"),
        ),
    ]
