# Generated by Django 5.2 on 2025-05-05 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_listing', '0002_remove_carlisting_featured_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carlisting',
            old_name='colors',
            new_name='exterior_colors',
        ),
        migrations.AddField(
            model_name='carlisting',
            name='comfort_convenience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carlisting',
            name='entertainment_communication',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carlisting',
            name='exterior_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carlisting',
            name='interior_colors',
            field=models.CharField(default=datetime.datetime(2025, 5, 5, 12, 53, 19, 832425, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carlisting',
            name='interior_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carlisting',
            name='safety',
            field=models.TextField(blank=True, null=True),
        ),
    ]
