# Generated by Django 5.2 on 2025-05-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_listing', '0003_rename_colors_carlisting_exterior_colors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardealer',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cardealer',
            name='location_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
