# Generated by Django 5.2 on 2025-07-13 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_listing', '0004_cardealer_is_verified_cardealer_location_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carlisting',
            name='original_price',
        ),
    ]
