# Generated by Django 6.0 on 2026-01-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Why Choose Isam Auto', max_length=255)),
                ('description', models.TextField(default='Over the Years, we have done a great amount of research on the market to determine our customers’ needs. Based on the report, we have been buying varieties of vehicles with different price ranges to accommodate those needs. We keep offering our vehicles at less than the market, because we believe in building long-term relationships with our customers through our value based repair services.')),
                ('feature_1_title', models.CharField(default='Free Buyer’s Inspection', max_length=255)),
                ('feature_2_title', models.CharField(default='Interest Free Payment Flexibility', max_length=255)),
                ('feature_3_title', models.CharField(default='59 Seconds of Paperwork', max_length=255)),
                ('content_title_1', models.CharField(default='Free Buyer’s Inspection', max_length=255)),
                ('content_description_1', models.TextField(default='Know exactly what you are buying')),
                ('content_icon_1', models.ImageField(blank=True, null=True, upload_to='about/icons/')),
                ('content_title_2', models.CharField(default='Payment Flexibility', max_length=255)),
                ('content_description_2', models.TextField(default='Not enough budget? Buy & Pay Later without Paying any Interest')),
                ('content_icon_2', models.ImageField(blank=True, null=True, upload_to='about/icons/')),
                ('content_title_3', models.CharField(default='Trade on Spot', max_length=255)),
                ('content_description_3', models.TextField(default='Wanna Get Rid of your Humpty Dumpty? Try Us!')),
                ('content_icon_3', models.ImageField(blank=True, null=True, upload_to='about/icons/')),
                ('content_image1', models.ImageField(blank=True, null=True, upload_to='about/images/')),
                ('content_image2', models.ImageField(blank=True, null=True, upload_to='about/images/')),
            ],
        ),
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.TextField()),
                ('hero_image', models.ImageField(help_text='Recommended size: 1700x900px', upload_to='page_content/hero_banners/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScrollBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
    ]
