# Generated by Django 6.0 on 2026-01-04 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car_listing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('dob_or_registerdate', models.DateField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('marital_status', models.CharField(max_length=50)),
                ('sin', models.CharField(max_length=255)),
                ('street_name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=50)),
                ('address_duration', models.CharField(max_length=50)),
                ('home_ownership', models.CharField(max_length=50)),
                ('applicant_type', models.CharField(choices=[('applicant', 'Applicant'), ('co_applicant', 'Co-Applicant')], default='applicant', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car_name', models.ForeignKey(help_text='Which car this application is for', on_delete=django.db.models.deletion.PROTECT, related_name='loan_applications', to='car_listing.carlisting')),
                ('parent_applicant', models.ForeignKey(blank=True, help_text='Link to the main applicant if this is a co-applicant', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='co_applicants', to='loan_application.loanapplication')),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('length_of_employment', models.IntegerField()),
                ('street_name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('gross_monthly_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('company_number', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employment_info', to='loan_application.loanapplication')),
            ],
        ),
    ]
