# Generated by Django 5.2 on 2025-07-13 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_listing', '0005_remove_carlisting_original_price'),
        ('loan_application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='car_name',
            field=models.ForeignKey(help_text='Which car this application is for', on_delete=django.db.models.deletion.PROTECT, related_name='loan_applications', to='car_listing.carlisting'),
        ),
    ]
